### ISSUE TITLE
`while` condition for wait function in docker_container.rb does not work with Docker API Version 1.2.3

### ISSUE THREAD

**Issue by fonglh** [Coursemology/evaluator-slave#49]
``` 
   while container_state.fetch('State', {}).fetch('Running', true)
      super
      refresh!
      container_state = info
    end
```

In Docker API version 1.2.3 and greater, `State` is no longer a hash of various true/false values for the container state. Instead, it seems to be a string with the state.

Thus the tests fail with the error:

```
Failure/Error: while container_state.fetch('State', {}).fetch('Running', true)

     NoMethodError:
       undefined method `fetch' for "exited":String
```

One possible solution is to change the condition to `while container_state.fetch('State', {}) != 'exited'`
This will break compatibility with older versions of the Docker API.

Also, more investigation needs to be done to determine the other possible states and see if `exited` is the most suitable.

**Comment by lowjoel** [comment]
Can you dig the API docs as to why this was changed?

**Comment by fonglh** [comment]
For the endpoint GET containers/**&lt;container-id&gt;**/json, Docker API 1.2.2 and Docker API 1.2.3 both have the `State` hash which looks like

```"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":3235,"ExitCode":0,"Error":"","StartedAt":"2016-07-08T10:43:22.246989707Z","FinishedAt":"0001-01-01T00:00:00Z"}```

This is the behaviour the evaluator needs.

Docker API 1.2.3 added a `State` key for GET containers/json.

```"State":"running"```

I'm guessing that the Docker API gem grabs the first value of `State` it encounters. Previously it was forced to iterate through container IDs to get that value, now it doesn't. I'll try to find out how the gem is getting the info.

**Comment by fonglh** [comment]
From the [refresh!](https://github.com/swipely/docker-api/blob/5c677411fa9ba9dbb4a52e378f48cac4f9abf9bc/lib/docker/container.rb#L8) function of the docker-api gem,

```
def refresh!
    other = Docker::Container.all({all: true}, connection).find { |c|
      c.id.start_with?(self.id) || self.id.start_with?(c.id)
    }

    info.merge!(self.json)
    other && info.merge!(other.info)
    self
end
```

`Docker::Container.all({all:true}, connection)` calls GET v1.16/containers/json?all=1. It then looks for the container ID and stores the information for that container in `other`.

`self.json` calls GET /v1.16/containers/&lt;container-id&gt;/json.

`info.merge!(other.info)` then overwrites duplicate keys in `info` with the keys in `other`.

[Docker API v1.2.3 changes](https://docs.docker.com/engine/reference/api/docker_remote_api/#/v1-23-api-changes) says

>GET /containers/json returns the state of the container, one of created, restarting, running, paused, exited or dead

so the value of the `State` key in `other` is replacing the value of `State` from `self.json`, causing the evaluator's check of the container status to fail.

[Docker's documentation](https://docs.docker.com/engine/reference/api/docker_remote_api/) says it's possible to call old versions of the API
> The current version of the API is v1.24 which means calling /info is the same as calling /v1.24/info. To call an older version of the API use /v1.23/info.

and the docker-api gem is trying to do that by pinning down the version of the Docker API used.

However, Docker's API does **NOT** respect the API version in the URL.

To verify, here is command line output from a machine with Docker API version 1.2.4.
Regardless of whether the API version is specified, both return `State`.

```
 ~$  docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true
 ~$  curl --unix-socket /var/run/docker.sock http:/containers/json
[{"Id":"b6655861570c3d37eec22aa4598b685bf0cd3b7fd870c56b835ef081de094c43","Names":["/zen_noether"],"Image":"ubuntu","ImageID":"sha256:12543ced0f6f754223eff4cca67b56cbf9f384456ab9deaa824ba9ff28bcfdd6","Command":"bash","Created":1468313076,"Ports":[],"Labels":{},"State":"running","Status":"Up About an hour","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"dfddde6472aac68727b764d95aa8f613075db2b9dc692051c1135340d0532f7a","EndpointID":"4e43509259ce8b079852c3530ad76de9b1cf667602b29c8d7f47fbd0a7d0926e","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[]}]
 ~$  curl --unix-socket /var/run/docker.sock http:/v1.22/containers/json
[{"Id":"b6655861570c3d37eec22aa4598b685bf0cd3b7fd870c56b835ef081de094c43","Names":["/zen_noether"],"Image":"ubuntu","ImageID":"sha256:12543ced0f6f754223eff4cca67b56cbf9f384456ab9deaa824ba9ff28bcfdd6","Command":"bash","Created":1468313076,"Ports":[],"Labels":{},"State":"running","Status":"Up About an hour","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"dfddde6472aac68727b764d95aa8f613075db2b9dc692051c1135340d0532f7a","EndpointID":"4e43509259ce8b079852c3530ad76de9b1cf667602b29c8d7f47fbd0a7d0926e","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[]}]
```

The following output is from a machine with an older version of the Docker API. This version of the same endpoints does not return `State`.

```
~$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
~$ curl --unix-socket /var/run/docker.sock http:/containers/json
[{"Id":"6dd0621a07e7355ad28c2ddb3bfa73327e4f03c52560af7ff4d8f109ace5f765","Names":["/furious_meninsky"],"Image":"ubuntu","ImageID":"sha256:0f192147631d72486538039c51ef9557be11865030be2951a0fbe94ef66db618","Command":"bash","Created":1468314567,"Ports":[],"Labels":{},"Status":"Up 58 minutes","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"","EndpointID":"0531355c66603efff5631055e22bfdd27e4dad7b40b400a30dc5c61cb88aea7b","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}}}]
~$ curl --unix-socket /var/run/docker.sock http:/v1.22/containers/json
[{"Id":"6dd0621a07e7355ad28c2ddb3bfa73327e4f03c52560af7ff4d8f109ace5f765","Names":["/furious_meninsky"],"Image":"ubuntu","ImageID":"sha256:0f192147631d72486538039c51ef9557be11865030be2951a0fbe94ef66db618","Command":"bash","Created":1468314567,"Ports":[],"Labels":{},"Status":"Up 58 minutes","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"","EndpointID":"0531355c66603efff5631055e22bfdd27e4dad7b40b400a30dc5c61cb88aea7b","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}}}]
```

**Comment by lowjoel** [comment]
@fonglh remember to open PRs to revert the two merges above after it is fixed upstream.

**Comment by fonglh** [comment]
Fixed in swipely/docker-api#418.

Docker versions above 1.10.x will require Docker API gem version >=1.29.1
